apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: kubernetes-project
  name: kubernetes-project
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubernetes-project
    spec:
      containers:
      - image: nethmitharushika99/it19152288:latest
        imagePullPolicy: Always
        name: it19152288
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports: 
          - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always